---
# tasks file for python
- name: Install python3
  apt:
    name: python3
    state: latest
    update_cache: yes

- name: Install pip
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
